export const texts ={
  signUpTitle:{"pt-PT":"Inscrever-se","en-US":"Sign-up"},
  loginTitle:{"pt-PT":"Conecte-se","en-US":"Login"},
  dashboard:{"pt-PT":"Painel","en-US":"Dashboard"},
  shrunken:{"pt-PT":"Encolhido","en-US":"Shrunken"},
  home:{"pt-PT":"Casa","en-US":"Home"},
  aboutUsTitle:{"pt-PT":"Sobre nós","en-US":"About-us"},
  reviewsTitle:{"pt-PT":"Críticas","en-US":"Reviews"},
  termsOfConditionTitle:{"pt-PT":"Termos de condição","en-US":"Terms of condition"},
  privacyPolicyTitle:{"pt-PT":"Política de Privacidade","en-US":"Privacy policy"},
  contactUsTitle:{"pt-PT":"Contacte nos","en-US":"Contact us"},
  footerQuote:{"pt-PT":"Adoramos fazer parte da sua liberdade financeira.","en-US":"We love being part of your financial freedom"},
  subscribeText:{"pt-PT":"Cadastre-se para receber novidades em primeira mão.","en-US":"Sign up to receive news first hand."},
  subscribe:{"pt-PT":"Inscrever-se","en-US":"Subscribe"},
  footerTitleA:{"pt-PT":"Links Rápidos","en-US":"Quick Links"},
  footerTitleB:{"pt-PT":"Empresa","en-US":"Company"},
  paymentGateways:{"pt-PT":"Gateways de pagamento","en-US":"Payment gateways"},
  paymentInstantly:{"pt-PT":"Pagamento instantâneo","en-US":"Payment instantly"},
  now:{"pt-PT":"agora","en-US":"now"},
  yesAndNot:{"pt-PT":["Sim","Não"],"en-US":["Yes","Not"]},
  active:{"pt-PT": "Ativo","en-US":"Active"},
  inactive:{"pt-PT": "Inativo","en-US":"Inactive"},
  findOutMore:{"pt-PT":"Descubra mais", "en-US":"Find out more"},
  and:{"pt-PT":"e","en-US":"and"},
  edit:{"pt-PT":"Editar","en-US":"Edit"},
  footerTitleC:{"pt-PT":"Contatos","en-US":"Contacts"},
  testimonialsTitle:{"pt-PT":"O que dizem sobre nós","en-US":"Testimonials"},
  headerTitleA:{"pt-PT":"Ganha", "en-US":"Earns"},
  headerTitleB:{"pt-PT":"dinheiro","en-US":"money"},
  headerTitleC:{"pt-PT":"investindo na indústria avícola.","en-US":"by investing in the poultry industry."},
  headerParagraph:{"pt-PT":"Com o crescimento da indústria avícola, investir nesse setor é uma oportunidade lucrativa.","en-US":"With the growth of the poultry industry, investing in this sector is a profitable opportunity."},
   
  startNow:{"pt-PT": "Começar agora","en-US":"Start now"},
  packagesTitleA:{"pt-PT":"A escolha perfeita para","en-US":"The perfect choice for"},
  packagesTitleB:{"pt-PT":"pessoas de negócios","en-US":"business people"},
  packagesTitleC:{"pt-PT":"como você","en-US":"like you."},
  packagesParagraph:{"pt-PT":"Escolhe a sua frota e começa já a sua jornada de investimentos em avicultura online.","en-US":"Choose your fleet and start your online poultry farming investment journey now."},
  packagesParagraphB:{"pt-PT":"Escolhe uma frota de investimento que melhor se adequa ao teu perfil pra começar.","en-US":"Choose an investment fleet that best suits your profile to get started."},
  packageDetailsA:{"pt-PT":"Do seu dinheiro em","en-US":"Your money in "},
  packageDetailsB:{"pt-PT":"dias úteis","en-US":"business days"},
  max:{"pt-PT":"Máxima","en-US":"Maximum"},
  min:{"pt-PT":"Mínimo","en-US":"Minimum"},
  packageBtn:{"pt-PT":"Investir agora","en-US":"Invest now"},
  featuresTitleA:{"pt-PT":"Existem tantas opções no mercado, mas aqui estão as","en-US":"There are so many options on the market, but here's are"},
  featuresTitleB:{"pt-PT":"razões pelas quais","en-US":"reason why"},
  featuresTitlec:{"pt-PT":"você deve nos escolher.","en-US":"you should choose us."},
  featuresParagraph:{"pt-PT":"Entendemos as tendências do mercado e os requisitos de criação, garantimos o sucesso do seu investimento.","en-US":"We understand market trends and creation requirements, we guarantee the success of your investment."},
  features:[
  { icon:"bi bi-lightbulb",
    title:{"pt-PT":"Sobre nós","en-US":"About Us"},
    paragraph:{"pt-PT":"Há mais de 8 anos trabalhamos com um amplo leque de empresas sendo uma ótima alternativa ao desenvolvimento avícola", "en-US":"We have been working with a wide range of companies for over 8 years, being a great alternative to poultry development."}
  },{
    icon:"bi bi-bullseye",
    title:{"pt-PT":"Nossa missão","en-US":"Our mission"},
    paragraph:{"pt-PT":"Todos nós compartilhamos a mesma missão - ter nossos clientes leais felizes e satisfeitos com seus produtos em pleno funcionamento.", "en-US":"We all share the same mission - to have our loyal customers happy and satisfied with our fully functioning products."}
  },{
    icon:"bi bi-eye",
    title:{"pt-PT":"Nossa visão","en-US":"Our vision"},
    paragraph:{"pt-PT":"É ter um mercado onde todos os nossos sócios e colaboradores tenham oportunidades iguais de crescimento financeiro por meio de nossos serviços e produtos.", "en-US":"It means having a market where all our partners and employees have equal opportunities for financial growth through our services and products."}
  },{
    icon:"bi bi-heart",
    title:{"pt-PT":"Equipe qualificada","en-US":"Qualified team"},
    paragraph:{"pt-PT":"Nossos profissionais irão garantir a melhor experiência de investimentos, considerando seus objetivos de negócio", "en-US":"Our professionals will guarantee the best investment experience, considering your business objectives"}
  }],
  notFoundTitle:{"pt-PT":"Parece que você está perdido", "en-US":"Looks like you're lost"},
  notFoundtext:{"pt-PT": "A página que você está procurando não está disponível!", "en-US":"The page you are looking for is not available!"},
  goToBack:{"pt-PT":"Voltar para atrás", "en-US":"Go to back"},
  copyrigths:{"pt-PT":"Todos os direitos reservados","en-US":"All rights reserved."},
  reviewsHeaderTitleA:{"pt-PT":"Explora","en-US":"Explore"},
  reviewsHeaderTitleB:{"pt-PT":"o que dizem","en-US":"what they say"},
  reviewsHeaderTitleC:{"pt-PT":"sobre nós.","en-US":"about us."},
  reviewsHeaderParagraph:{"pt-PT":"Algumas palavras sobre por que nos escolheram e aos nossos serviços. Saiba mais verificando avaliações de nossos clientes","en-US":"A few words about why they chose us and our services. Find out more by checking our customer reviews"},
  makeAnReviews:{"pt-PT":"Escrever uma crítica","en-US":"Write a review"},
  makePublic:{"pt-PT":"Publicar","en-US":"Make public"},
  newReviewTitle:{"pt-PT":"Dê-nos a sua opinião","en-US":"Give us your opinion"},
  reviewLabel:{"pt-PT":"Escreva a sua crítica","en-US":"Write your review"},
  errorReviewText:{"pt-PT":"Este campo deve ter pelo menos 50 caracteres.","en-US":"This field must be at least 50 characters long."},
  containHtml:{"pt-PT":"Caracteres especiais detectados, por favor revise este campo","en-US":"Special characters detected, please review this field"},
  seeMore:{"pt-PT":"Ver mais","en-US":"See more"},
  totalPages:{"pt-PT":"Total de páginas","en-US":"Total pages"},
  
  fleetsTitle:{"pt-PT":"Frotas","en-US":"Fleets"},
  newFleet:{"pt-PT":"Nova frota","en-US":"New fleet"},
  newGateway:{"pt-PT":"Novo gateway", "en-US":"New gateway"},
  updateTitle:{"pt-PT":"Atualizar","en-US":"Update"},
  name:{"pt-PT":"Nome","en-US":"Name"},
  accountOwner:{"pt-PT":"Proprietário da conta", "en-US":"Account owner"},
  maturity:{"pt-PT":"Dias para vencimento","en-US":"Days to expiration"},
  percentage:{"pt-PT":"Percentagem","en-US":"Percentage"},
  cannotBe0OrNull:{"pt-PT":"não pode ser 0 ou nulo","en-US":"cannot be 0 or null"},
  confirmDFleetTitle:{"pt-PT":"Tens certeza que deseja excluir esta frota?","en-US":"Are you sure you want to delete this fleet?"},
  confirmDFleetText:{"pt-PT":"Esta frota pode ter depósitos dos usuários, todos os depósitos feitos nesta frota serão excluídos permanentemente.","en-US":"This fleet may have user deposits, all deposits made to this fleet will be permanently deleted."},
  _delete:{"pt-PT":"Excluir","en-US":"Delete"},
  confirmLogOut:{"pt-PT":"Tens certeza que deseja sair?","en-US":"Are you sure you want to leave?"},
  confirmReveseReview:{"pt-PT":"Tem certeza de que deseja deixar estas avaliações pública?","en-US":"Are you sure you want to make these reviews public?"},
  confirmUnreveseReview:{"pt-PT":"Tem certeza que deseja não deixar essas avaliações públicas?","en-US":"Are you sure you don't want to make these reviews public?"},
  dangerReveseReview:{"pt-PT":"Todas as avaliações revisadas são públicas. Isso significa que qualquer usuário pode lê-las.","en-US":"All revesed reviews are public. This means that any user can read them."},
  doNotPublish:{"pt-PT":"Não publique","en-US":"Do not publish"},
  confirmsUser:{"pt-PT":["Tens certeza que deseja", "este usuário?"],"en-US":["Are you sure you want to","this user?"]},
  dangerBanUser:{"pt-PT":"Ao banir este usuário significa que ele ainda pode fazer login, mas não vai poder realizar certas operações.","en-US":"By banning this user it means that he can still log in, but will not be able to perform certain operations."},
  reactivate:{"pt-PT":"Reativar","en-US":"Reactivate"},
  userUpdatedSuccessfully:{"pt-PT":["Usuário","com sucesso."],"en-US":["User" ,"successfully."]},
  reactivated:{"pt-PT":"Reativado", "en-US":"Reactivated"},
  banned:{"pt-PT":"Banido", "en-US":"Banned"},
  
  calcTitle:{"pt-PT":"Calcular ganhos", "en-US":"Calculate earnings"},
  newWithdrawalTitle:{"pt-PT":"Novo saque","en-US":"New withdrawal"},
  payMethodTitle:{"pt-PT":"Método de pagamento ","en-US":"Payment method"},
  amount:{"pt-PT":"Valor", "en-US":"Amount"},
  accountNumberTitle:{"pt-PT":"Número da conta","en-US":"Account number"},
  account:{"pt-PT":"Conta","en-US":"Account"},
  saveThisAccountTitle:{"pt-PT":"Guardar essa conta para utilizar nas próximas transações?","en-US":"Save this account to use in future transactions?"},
  invalidMpesaAccount:{"pt-PT":"Conta do m-pesa inválido", "en-US":"Invalid m-pesa account"},
  invalidEmolaAccount:{"pt-PT":"Conta do e-mola inválido ", "en-US":"Invalid e-mola account"},
  invalid:{"pt-PT":"Inválido", "en-US":"Invalid"},
  accountAlreadyUsed:{"pt-PT":"Esta conta já está em uso por outro usuário.","en-US":"This account is already in use by another user."},
  noDepositsMadeWith:{"pt-PT":"Nenhum depósito feito com está conta ou já foi usado por outro usuário.","en-US":"No deposits have been made with this account or it has already been used by another user."},
  thankYou:{"pt-PT":"Obrigado(a)","en-US":"Thank you"},
  orderWasPlaced:{"pt-PT":"O seu pedido foi realizado com sucesso","en-US":"Your order was placed successfully"},
  confirmationProvider:{"pt-PT":"Aguardamos a confirmação da sua operadora de pagamentos.","en-US":"We await confirmation from your payment provider."},
  sorry:{"pt-PT":"Desculpa","en-US":"Sorry"},
  requestWasRejected:{"pt-PT":"O seu pedido foi rejeitado.", "en-US":"Your request was rejected"},
  unableToFulfill:{"pt-PT":"Infelizmente não conseguimos atender sua solicitação.","en-US":"Unfortunately we were unable to fulfill your request."},
  hasBeenBanned:{"pt-PT":"Sua conta foi banida nesta plataforma.","en-US":"Your account has been banned on this platform."},
  hasBeenReactivated:{"pt-PT":"Sua conta foi reativada, agora você pode realizar suas atividades na plataforma.", "en-US":"Your account has been reactivated, you can now carry out your activities on the platform."},
  hasVoided:{"pt-PT":"A sua transação foi revertida.","en-US":"Your transaction has been reversed."},
  hasBeenRejected:{"pt-PT":"A sua transação foi rejeitado", "en-US":"Your transaction has been rejected"},
  _continue:{"pt-PT": "Continuar","en-US":"Continue"},
  _package:{"pt-PT":"Pacote","en-US":"Package"},
  income:{"pt-PT":"Renda", "en-US": "Income"},
  fullRefund:{"pt-PT":"Devolução total", "en-US":"Full refund"},
  totalIncome:{"pt-PT":"Renda total", "en-US": "Total income"},
  totalReceived:{"pt-PT":"Total recebido", "en-US":"Total received"},
  totalToReceive:{"pt-PT":"Total a receber", "en-US":"Total to receive"},
  fee:{"pt-PT":"Taxa", "en-US":"Fee"},
  returnDay:{"pt-PT":"Retorno em", "en-US":"Return at"},
  lowAmount:{"pt-PT":"O valor mínimo necessário para depositos nesta frota é", "en-US":"The minimum amount required for deposits in this fleet is"},
  exceededAmount:{"pt-PT":"O quantia ultrapassou o máximo","en-US":"The amount exceeded the maximum"},
  important:{"pt-PT":"Importante","en-US":"Important"},
  guideManualPaymentA:{"pt-PT":"Envie o dinheiro para a conta abaixo.","en-US":"Send the money to the account below."},
  guideManualPaymentB:{"pt-PT":"Envia uma captura de tela de prova de pagamento no","en-US":"Sends  screen shot of payment proof in the"},
  guideManualPaymentNote:{"pt-PT":"Se o número da conta do comprovante de pagamento não for o mesmo usado neste depósito, seu depósito não será aprovado.","en-US":"If the proof of payment account number is not the same as used in this deposit, your deposit will not be approved."},
  
  
  timeUnits:{"pt-PT":["Agora","minuto","hora","dia","mês","ano"],"en-US": ["now","minute","hour","day","month","year"]},
  ago:{"pt-PT":"atrás","en-US":"ago"},
  gretings:{"pt-PT": "Olá!", "en-US":"Hello!"},
  transactionHeader:{"pt-PT":"Todas as suas transações encontram-se aqui, desde depositos, saques, e comissões.","en-US":"All your transactions are here, deposits, withdrawals, and commissions."},
  loadingMsg:{"pt-PT":"Carregando...","en-US":"Loading..."},
  searchByUserId:{"pt-PT":"Pesquisar por ID de usuário","en-US":"Search by user id"},
  searchByDataId:{"pt-PT":"Pesquisar por ID","en-US":"Search by id"},
  search:{"pt-PT":"Pesquisar","en-US":"Search"},
  viewSource:{"pt-PT":"Ver a origem","en-US":"View source"},
  Pending:{"pt-PT":"Pendente","en-US":"Pending"},
  Rejected:{"pt-PT":"Rejeitado","en-US":"Rejected"},
  Voided:{"pt-PT":"Anulado", "en-US":"Voided"},
  Matured:{"pt-PT":"Amadurecido","en-US":"Matured"},
  Process:{"pt-PT":"Processar","en-US":"Process"},
  Reject:{"pt-PT":"Rejeitar","en-US":"Reject"},
  Void:{"pt-PT":"Anular","en-US":"Void"},
  Inprogress:{"pt-PT":"Em andamento","en-US":"Inprogress"},
  Completed:{"pt-PT":"Concluído","en-US":"Completed"},
  ProcessParag:{
    deposit:{"pt-PT":"Ao processar este depósito significa que você está prestes a adicionar o valor total do reembolso para este usuário.","en-US":"Processing this deposit means you are about to add the full refund amount for this user."},
    withdrawal:{"pt-PT":"Ao processar esta retirada significa que você está prestes a enviar o dinheiro para uma conta eletrônica específica nesta retirada ou já enviou em off, e esta ação não será cancelada.","en-US":"By processing this withdrawal means that you are about to send the money to a specific electronic account in this withdrawal or have already sent it offline, and this action will not be canceled."},
    commission:{"pt-PT":"Ao processar esta comissão significa que você está prestes a adicionar o valor da comissão para este usuário.", "en-US":"By processing this commission means you are about to add the commission amount for this user."}
  },
  ConfirmParag:{"pt-PT":["Tem certeza que deseja confirmar esse deposito?\nTenha certeza que este usuário enviou na plataforma o valor correspondente a", "ou troque embaixo."],"en-US":["Are you sure you want to confirm this deposit?\nMake sure that this user has sent the corresponding", "amount to the platform or exchange below."]},
  cancel:{"pt-PT":"Cancelar","en-US":"Cancel"},
  Confirm:{"pt-PT":"Confirmar","en-US":"Confirm"},
  voidParag:{
    deposit:{"pt-PT":"Ao anular este depósito significa que o depósito não estará na lista de espera nem nos depósitos imaturos.","en-US":"Voiding this deposit means that the deposit will not be on the waiting list or in the immature deposits."},
    withdrawal:{"pt-PT":"Ao anular este saque significa que o dinheiro será devolvido à conta do usuário, esta ação não será cancelada.","en-US":"By Voiding this withdrawal means that the money will be returned to the user's account, this action will not be cancelled."},
    commission:{"pt-PT": "Ao anular esta comissão significa que o usuário não receberá esta comissão, esta ação não será cancelada.","en-US":"By Voiding this commission means that the user  will not receive this  commission, this action will not be cancelled."},
  },
  RejectParag:{"pt-PT":"Tens certeza que deseja rejeitar esse","en-US":"Are you sure you want to reject this"},
  deposit:{"pt-PT":"Depósito","en-US":"Deposit"},
  withdrawal:{"pt-PT":"Saque","en-US":"Withdrawal"},
  commission:{"pt-PT":"Comissão","en-US":"Commission"},
  withdrawals:{"pt-PT":"Saques","en-US":"Withdrawals"},
  deposits:{"pt-PT":"Depósitos","en-US":"Deposits"},
  commissions:{"pt-PT":"Comissões","en-US":"Commissions"},
  rejectedPaymentWarn:{"pt-PT":"Rejeitado pelo sistema de pagamento.\nEntre em contato com seu banco e faça uma nova solicitação ou tente outro sistema de pagamento.","en-US":"Rejected by the payment system.\nPlease either contact your bank and make new request or try another payment system."},
  voidedPaymentWarn:{"pt-PT":"Por razões de irregularidades o valor foi revertido, talvez você não está classificado para receber este valor.", "en-US":"Due to irregularities the amount was reversed, you may not be eligible to receive this amount."},
  confirmedDepositWarn:{"pt-PT":"Seu depósito foi confirmado e o valor está em produção, após o vencimento, seu saldo estará disponível para retirada." ,"en-US":"Your deposit has been confirmed and the amount is in production, after maturity your balance will be available for withdrawal."},
  depositsInQueueWarn:{"pt-PT":"Aguardando pelo pagamento. Por favor siga as instruções para completar o seu depósito." ,"en-US" :"Waiting for payment. Please follow the instructions to complete your deposit."},
  withdrawalsInQueueWarn:{"pt-PT":"O seu saque está na fila. Isso pode levar 48 horas ou 7 dias úteis. Pedimos que você tenha muita paciência." ,"en-US":"Your withdrawal is in the queue. This may take 48 hours or 7 business days. We ask you to be patience."},
  commissionsInQueueWarn:{"pt-PT":"Sua comissão está na fila, sua confirmação depende muito mais da confirmação do depósito do seu downline.","en-US":"Your commission is in the queue, its confirmation depends much more on the confirmation of your downline's deposit."},
  tryAgain:{"pt-PT":"Tente novamente","en-US":"Try again "},
  contactSupport:{"pt-PT":"Contactar suporte", "en-US":"Contact support"},
  commissionAdded:{"pt-PT":"Comissão adicionado ao saldo do usuário.","en-US":"Commission added to user balance."},
  confirmedSuccessfully:{"pt-PT":"confirmado com sucesso.", "en-US":"successfully confirmed."},
  CompletedSuccessfully:{"pt-PT":"concluído com sucesso.", "en-US":"successfully completed."},
  VoidedSuccessfully:{"pt-PT":"revertido com sucesso.", "en-US":"successfully reversed."},
  RejectedSuccessfully:{"pt-PT":"rejeitado com sucesso.","en-US":"rejected successfully."},
  support:{"pt-PT":"Suporte", "en-US":"Support"},
  startAConversation:{"pt-PT":"Inicia uma conversar","en-US":"Start a conversation."},
  createdAt:{"pt-PT":"Criado em", "en-US":"Created at"},
  fleet:{"pt-PT":"Frota","en-US":"Fleet"},
  showToThePublic:{"pt-PT":"Mostrar para o público","en-US":"Show to the public"},
  maturityDate:{"pt-PT":"Data de vencimento","en-US":"Maturity date"},
  nothingWasFound:{"pt-PT":"Nada foi encontrado!", "en-US":"Nothing was found!"},
  financialComission:{"pt-PT":"Parabéns, você ganhou uma comissão", "en-US":"Congratulations, you have earned commission bonus!"},
  financialBonus:{"pt-PT":"Parabéns, você ganhou bonus de boas vindas", "en-US":"Congratulations, you have earned welcome bonus!"},
  userInfos:{"pt-PT":"Informação de usuário","en-US":"User infos"},
  emailAddress:{"pt-PT":"Endereço de email","en-US":"Email address"},
  memberSince:{"pt-PT":"Membro desde","en-US":"Member since"},
  location:{"pt-PT":"Localização","en-US":"Location"},
  ProfileID:{"pt-PT":"ID do perfil","en-US":"Profile ID"},
  settings:{"pt-PT":"Configurações", "en-US": "Settings"},
  logout:{"pt-PT":"Sair","en-US":"Logout"},
  changePassword:{"pt-PT":"Trocar senha","en-US":"Change password"},
  balance:{"pt-PT":"Saldo","en-US":"Balance"},
  balanceAvailable:{"pt-PT":"Saldo disponível","en-US":"Balance available"},
  lowBalance:{"pt-PT":"Você não tem saldo suficiente para sacar","en-US":"You don't have enough balance to withdraw"},
  unspecifiedBalance:{"pt-PT":"O mínimo montante para o saque são 50.00 MZN","en-US":"The minimum amount for withdrawal is 50 MZN"},
  depositNow:{"pt-PT":"Depositar","en-US":"Deposit"},
  withdrawNow:{"pt-PT":"Sacar","en-US":"Withdraw"},
  phoneNumber:{"pt-PT":"Número de Telefone","en-US":"Phone number"},
  notProvidedYet:{"pt-PT":"Ainda não fornecido","en-US":"Not provided yet"},
  bankAccount:{"pt-PT":"Conta bancária","en-US":"Bank account"},
  imageNotsupported:{"pt-PT":"O arquivo selecionado não é suportada!","en-US":"The selected file is not supported!"},
  imageProfile:{"pt-PT":"Imagem de perfil","en-US":"Profile image"},
  image:{"pt-PT":"Imagem","en-US":"Image"},
  actionNotAllowed:{"pt-PT":"Ação não permitido.","en-US":"Action not allowed."},
  errorGettingCroppedImg:{"pt-PT":"Erro ao obter a imagem cortado.","en-US":"Error getting cropped image."},
  cropperIsNotResponding:{"pt-PT":"O cortador de imagens não está respondendo.","en-US":"Image cropper is not responding."},
  imagens:{"pt-PT":"Imagems","en-US":"Imagens"},
  editName:{"pt-PT":"Editar o nome","en-US":"Edit Name"},
  editPhoneNumber:{"pt-PT":"Editar número de telefone","en-US":"Edit phone number"},
  fullName:{"pt-PT":"Nome completo","en-US": "Full name"},
  invalidEmail:{"pt-PT":"Endereço de e-mail inválido!","en-US":"Invalid email!"},
  invalidFullName:{"pt-PT":"Nome completo inválido", "en-US":"Invalid full name"},
  invalidPhoneNumber:{"pt-PT":"Número de telefone inválido","en-US":"Invalid phone number"},
  deleteAccount:{"pt-PT":"Deletar esta conta","en-US": "Delete this account"},
  successfulDeletetAccount:{"pt-PT":"Conta deletado com sucesso.","en-US": "Account deleted successful."},
  successfulPasswordChenged:{"pt-PT":"Senha alterado com sucesso.","en-US":"Password changed successfully."},
  save:{"pt-PT":"Salvar","en-US": "Save"},
  resetPasswordTitle:{"pt-PT":"Redefinir senha","en-US":"Reset password"},
  welcomeBack:{"pt-PT":"Bem-vindo de volta!","en-US":"Welcome back!"},
  welcome:{"pt-PT":"Bem-vindo!","en-US":"Welcome!"},
  toBeLogging:{"pt-PT":"Ao fazer o login, você concorda com a nossa","en-US":"By logging in, you agree with our"},
  byRegistering:{"pt-PT":"Ao se cadastrar você concorda com os nossos","en-US":"By registering you agree to our"},
  byRequesting:{"pt-PT":"Ao solicitar uma redefinição de senha você concorda com nossos","en-US":"By requesting a password reset you agree to our"},
  byResetting:{"pt-PT":"Ao redefinir senha você concorda com nossos","en-US":"By resetting password you agree to our"},
  passwordLabel:{"pt-PT":"Senha", "en-US":"Password"},
  repeatPasswordLabel:{"pt-PT":"Repete a senha","en-US": "Repeat password"},
  invalidPassword:{"pt-PT":"Senha inválido","en-US":"Invalid password!"},
  passwordDontMatch:{"pt-PT":"As senhas não combinam!", "en-US":"Password don't match!"},
  emailAlreadyInUse:{"pt-PT":"O endereço de e-mail já está em uso por outra conta!" ,"en-US":"The email address is already in use by another account"},
  wrongPassword:{"pt-PT":"Senha incorreta","en-US":"Wrong password!"},
  tooManyRequests:{"pt-PT":"O acesso a esta conta foi temporariamente desabilitado devido a muitas tentativas de login malsucedidas. Você pode restaurá-lo imediatamente redefinindo sua senha ou pode tentar novamente mais tarde.","en-US":"Access to this account has been temporarily disabled due to many failed login attempts. You can immediately restore it by resetting your password or you can try again later."},
  requiresRecentLogin:{"pt-PT":"Esta operação é sensível e requer autenticação recente. Faça login novamente antes de tentar novamente esta solicitação.","en-US":"This operation is sensitive and requires recent authentication. Please log in again before retrying this request."},
  userNotFound:{"pt-PT":"Usuário não cadastrado!","en-US":"User not registered!"},
  weakPassword:{"pt-PT":"A senha deve ter pelo menos 6 caracteres", "en-US":"Password should be at least 6 characters!"},
  networkRequestFailed:{"pt-PT":"Falha na conexão a internet.","en-US":"Internet connection failure."},
  dontHaveAccount:{"pt-PT":"Não tens uma conta?", "en-US":"Don't have account?"},
  resend:{"pt-PT":"Reenviar novamente","en-US":"Resend again"},
  sendConfirmationEmail:{"pt-PT":"Enviamos lhe um email de confirmação da conta, por favor verifique a sua caixa de emails.","en-US":"We have sent you an account confirmation email, please check your inbox."},
  verifyYourAccount:{ "pt-PT":"Verifique a sua conta", "en-US":"Verify your account"},
  iHaveAccount:{"pt-PT":"Já tem uma conta?", "en-US": "Already have an account?"},
  forgotPassword:{"pt-PT":"Esqueceu sua senha?", "en-US":"Forgot password?"},
  request:{"pt-PT":"Solicitar", "en-US":"Request"},
  requestSent:{"pt-PT":"Solicitação enviada, por favor verifique a sua caixa de emails", "en-US":"Request sent, please check your email inbox"},
  rememberPassword:{"pt-PT":"Lembra da sua senha?","en-US":"Do you remember your password?"},
  transactions:{"pt-PT": "Transações", "en-US":"Transactions"},
  invites:{"pt-PT":"Convites","en-US":"Invites"},
  InvitesAfriend:{"pt-PT":"Convidar amigo","en-US":"Invite a friend"},
  me:{"pt-PT":"Eu","en-US":"My"},
  commissionAmount:{"pt-PT":"Comissão ganhada","en-US":"Earned commission"},
  invitedMembers:{"pt-PT":"Membros convidados","en-US":"Invited members"},
  activesMembers:{"pt-PT":"Membro Ativos","en-US":"Actives members"},
  refLinkTitle:{"pt-PT":"Copie o link de convite","en-US":"Copy the invitation link"},
  refLinkParaph:{"pt-PT":"Compartilhe com seus amigos e ganhe 5% por cada frota adquirida por seu amigo.","en-US":"Share with your friends and earn 5% for each fleet acquired by your friend."},
  thisMonth:{"pt-PT":"Este mês","en-US":"This month"},
  thisWeek:{"pt-PT":"Essa semana","en-US":"This week"},
  date:{"pt-PT":"Data","en-US":"Date"},
  depositAndWithdrawalHistory:{"pt-PT":"Histórico de depósitos e saques nos últimos 12 meses","en-US":"Deposit and withdrawal history in the last 12 months"},
  totalEarnings:{"pt-PT":"Ganhos totais","en-US":"Total earnings"},
  users:{"pt-PT":"Usuários","en-US":"Users"},
  totalUsers:{"pt-PT":"Usuários totais","en-US":"Total users"},
  administrators:{"pt-PT":"Administradores","en-US":"Administrators"},
  bannedUsers:{"pt-PT":"Usuários banidos","en-US":"Banned users"},
  ban:{"pt-PT":"Banir","en-US":"Ban"},
  notifications:{"pt-PT":"Notificações","en-US":"Notifications"},
  unreadMessages:{"pt-PT":["Você tem","mensagens não lidas."] , "en-US":["You have","unread messages."]},
  lastSeen:{"pt-PT":"Visto há","en-US":"Seen"},
  typing:{"pt-PT":"digitando...","en-US":"typing..."},
  text:{"pt-PT":"Texto","en-US":"Text"},
  searchChat:{"pt-PT":"Procurar chat","en-US":"Search chat"},
  heSentYouAPhoto:{"pt-PT":"Mandou uma foto 📷","en-US":"He sent you a photo 📷"},
  YouSentAPhoto:{"pt-PT":"Enviaste uma foto 📷","en-US":"You sent a photo 📷"},
  sendMessage:{"pt-PT":"Enviar mensagem","en-US":"Send message"},
  clearThisConversation:{"pt-PT":"Limpar essa conversa","en-US":"Clear this conversation"},
  confirmClearConversation:{"pt-PT":"Tens certeza que deseja limpar esta conversa?","en-US":"Are you sure you want to clear this conversation?"},
  clearNow:{"pt-PT":"Limpar agora","en-US":"Clear now"},
  chatClearedCuccessfully:{"pt-PT":"Conversa limpado com sucesso.","en-US":"Conversation cleared successfully."},
  confirmRemoveMsg:{"pt-PT":"Pretende eliminar essa mensagem?","en-US":"Do you want to delete this message?"},
  cannotBeUndone:{"pt-PT":"Essa ação não pode ser anulada","en-US":"This action cannot be undone"},
  viewProfile:{"pt-PT":"Ver o perfil","en-US":"View profile"},
  selected:{"pt-PT":"selecionados","en-US":"selected"},
  updateReviews:{"pt-PT":"Atualizar críticas","en-US":"Update reviews"},
  reviewsUpdatedSuccessfully:{"pt-PT":"Críticas atualizados com sucesso.","en-US":"Reviews updated successfully."},
  ppSubTitleA:{"pt-PT":"Bem-vindo(a) à nossa Política de Privacidade. Esta página informa sobre nossas práticas em relação à coleta, uso e divulgação de informações pessoais quando você utiliza nosso site e/ou serviços","en-US":"Welcome to our Privacy Policy. This page informs about our practices regarding the collection, use and dissemination of personal information when you use our website and/or services"},
  ppSubTitleB:{"pt-PT":"A proteção dos seus dados pessoais é uma prioridade para nós, e nos esforçamos para garantir a máxima segurança e confidencialidade em todas as interações.","en-US":"The protection of your personal data is a priority for us, and we strive to ensure maximum security and confidentiality in all interactions."},
  ppTitle1:{"pt-PT":"1. Coleta de Informações Pessoais","en-US":"1. Collection of personal information"},
  pp1_0:{"pt-PT":"Ao utilizar nosso site e ou nossos serviços, podemos coletar as seguintes informações pessoais:","en-US":"By using our website and/or our services, we may collect the following personal information:"},
  pp1_1:{"pt-PT":"Coletamos seu nome completo para identificação e personalização dos nossos serviços.", "en-US":"We collect your full name for identification and customization of our services."},
  pp1_2:{"pt-PT":"Coletamos seu endereço de e-mail para entrarmos em contato com você e para fins de comunicação relacionada aos nossos serviços.","en-US":"We collect your email address to contact you and for communication purposes related to our services."},
  pp1_3:{"pt-PT":"Se você optar por fornecer seu número de telefone, podemos usá-lo para entrar em contato com você sobre questões relacionadas a nossos serviços ou pagamentos eletrônicos.", "en-US":"If you choose to provide your phone number, we may use it to contact you regarding issues related to our services or for electronic payments."},
  pp1_4:{"pt-PT":"Para fins de pagamentos e transações financeiras, podemos solicitar suas informações bancárias. Todas as informações transmitidas são criptografadas e tratadas com o máximo de segurança","en-US":"For payments and financial transactions, we may request your banking information. All transmitted information is encrypted and treated with maximum security"},
  pp1_5:{"pt-PT":"Opcionalmente, podemos solicitar uma imagem de perfil para personalizar sua experiência conosco.", "en-US":"Optionally, we can request a profile picture to customize your experience with us."},
  pp1_6:{"pt-PT":"Coletamos informações sobre sua localização geográfica para fornecer serviços adaptados à sua região e para fins operacionais internos.","en-US":"We collect information about your geographic location to provide services tailored to your region and for internal operational purposes."},
  
  ppTitle2:{"pt-PT":"Uso das Informações Pessoais","en-US":"Use of personal information"},
  ppTitle2_0:{"pt-PT":"Utilizamos suas informações pessoais coletadas para:","en-US":"We use your personal information collected to:"},
  pp2_1:{"pt-PT":"Prestar nossos serviços e melhorar sua experiência como usuário;","en-US":"Provide our services and improve your experience as a user;"},
  pp2_2:{"pt-PT":"Entrar em contato com você para fins de suporte, atualizações e informações relacionadas aos nossos serviços;","en-US":"Contact you for support, updates and information related to our services;"},
  pp2_3:{"pt-PT":"Cumprir com obrigações legais, regulatórias ou judiciais, caso sejamos requisitados por um juiz ou autoridade competente;","en-US":"Comply with legal, regulatory or judicial obligations, if we are requested by a judge or competent authority;"},
  pp2_4:{"pt-PT":"Manter a segurança de nossos sistemas e salvaguardar a proteção de todos os usuários.","en-US":"Maintain the security of our systems and safeguard the protection of all users"},
  ppTitle3:{"pt-PT":"Compartilhamento de Informações Pessoais","en-US":"Sharing of personal information"},
  ppTitle3_0:{"pt-PT":"Podemos compartilhar suas informações pessoais nas seguintes circunstâncias:", "en-US":"We may share your personal information under the following circumstances:"},
  ppTitle3_1:{"pt-PT":"Com consentimento expresso:","en-US":"With express consent:"},   
  ppTitle3_2:{"pt-PT":"Para cumprir com obrigações legais:","en-US":"To comply with legal obligations:"},   
  ppTitle3_3:{"pt-PT":"Transferência de negócios:","en-US":"Business Transfer:"},   
  ppTitle3_4:{"pt-PT":"Com parceiros confiáveis:","en-US":"With trusted partners:"},   
  ppTitle3_5:{"pt-PT":"Anônimas e agregadas:","en-US":"Anonymous and aggregated:"},   
  
  pp3_1:{"pt-PT":"Quando obtivermos seu consentimento prévio e expresso para compartilhar informações pessoais específicas.","en-US":"When we obtain your prior and express consent to share specific personal information."},   
  pp3_2:{"pt-PT":"Podemos ser obrigados a divulgar suas informações pessoais em resposta a solicitações legais, processos judiciais ou cumprimento de leis.","en-US":"We may be required to disclose your personal information in response to legal requests, lawsuits or law enforcement."},   
  pp3_3:{"pt-PT":"Em caso de transferência, fusão ou venda de nossos ativos, suas informações pessoais podem ser transferidas aos terceiros envolvidos.","en-US":"In case of transfer, merger or sale of our assets, your personal information may be transferred to the third parties involved."},   
  pp3_4:{"pt-PT":"Podemos compartilhar suas informações pessoais com terceiros confiáveis que nos auxiliam na prestação de nossos serviços, desde que concordem em manter suas informações confidenciais e seguras.","en-US":"We may share your personal information with trusted third parties who assist us in the provision of our services, as long as they agree to keep your information confidential and secure."},   
  pp3_5:{"pt-PT":"Podemos compartilhar informações anônimas e agregadas sobre nossos usuários para fins estatísticos, publicitários ou outros.","en-US":"We may share anonymous and aggregated information about our users for statistical, advertising or other purposes."},   
 
  locationAddress:{"pt-PT":"Localização","en-US":"Location"},
  ppTitle4:{"pt-PT":"4. Segurança e Armazenamento de Dados","en-US":"4. Security and data storage"},
  pp4_1:{"pt-PT":"Tomamos medidas de segurança necessárias para proteger suas informações pessoais contra perdas, uso indevido e acesso não autorizado. Implementamos protocolos de segurança e criptografia para salvaguardar suas informações.","en-US":"We take necessary security measures to protect your personal information against loss, misuse and unauthorized access. We have implemented security protocols and encryption to safeguard your information."},
  pp4_2:{"pt-PT":"Armazenamos suas informações pessoais pelo tempo necessário para cumprir com os fins descritos nesta política. Quando não houver mais necessidade de reter suas informações, elas serão adequadamente descartadas.","en-US":"We store your personal information for as long as necessary to comply with the purposes described in this Policy. When there is no longer a need to retain your information, they will be properly discarded."},
  ppTitle5:{"pt-PT":"5. Seus Direitos e Opções","en-US":"5. Your rights and options"},
  pp5_1:{"pt-PT":"Você tem o direito de acessar, corrigir, atualizar e excluir suas informações pessoais. Caso deseje exercer seus direitos ou tenha outras perguntas relacionadas a esta política, entre em contato conosco através dos canais indicados no final desta página.","en-US":"You have the right to access, correct, update and delete your personal information. If you wish to exercise your rights or have other questions related to this policy, please contact us through the channels indicated at the bottom of this page."},
  ppTitle6:{"pt-PT":"Links Externos","en-US":"6. External links"},
  pp6_1:{"pt-PT":"Nosso site e serviços podem conter links para sites de terceiros. Esta Política de Privacidade aplica-se somente a nossos serviços e não podemos ser responsabilizados pelas práticas de privacidade desses sites externos. Recomendamos que você revise as políticas de privacidade desses sites antes de fornecer qualquer informação pessoal.","en-US":"Our website and services may contain links to third party websites. This Privacy Policy applies only to our Services and we cannot be held responsible for the privacy practices of these external websites. We recommend that you review the privacy policies of these sites before providing any personal information."},
  ppTitle7:{"pt-PT":"7. Alterações a esta Política de Privacidade","en-US":"7. Changes to this Privacy Policy"},
  pp7_1:{"pt-PT":"Podemos atualizar esta Política de Privacidade periodicamente para refletir mudanças em nossas práticas de privacidade. Recomendamos que você revise esta página regularmente para se manter informado(a) sobre qualquer alteração. Ao continuar a utilizar nosso site e/ou serviços após a publicação de quaisquer alterações nesta política, você estará aceitando essas modificações.","en-US":"We may update this Privacy Policy periodically to reflect changes in our privacy practices. We recommend that you review this page regularly to stay informed about any changes. By continuing to use our website and/or services after the publication of any changes to this policy, you will be accepting these changes."},
  ppTitle8:{"pt-PT":"Contato","en-US":"Contact"},
  pp8_1:{"pt-PT":"Se você tiver alguma pergunta, preocupação ou quiser exercer seus direitos relacionados à privacidade, entre em contato conosco através dos seguintes canais:","en-US":"If you have any questions, concerns or want to exercise your privacy-related rights, please contact us through the following channels:"},
  pp8_2:{"pt-PT":"Agradecemos por escolher a nossa empresa e confiar-nos as suas informações pessoais. Temos o compromisso de manter a segurança e a confidencialidade de seus dados.","en-US":"We thank you for choosing our company and entrust us with your personal information. We are committed to maintaining the security and confidentiality of your data."},
  
  
  tcTitle0:{"pt-PT":"Termos de condições ","en-US":"Terms of conditions"},
  tc0_0:{"pt-PT":`Ao se registrar na plataforma, esses termos se aplicarão automaticamente a você – portanto certifique-se de lê-los cuidadosamente antes de usar a plataforma.`,"en-US":`When you register with the platform, these terms will automatically apply to you – so make sure you read them carefully before using the platform.`},
  tcTitle1:{"pt-PT":"Direitos autorais","en-US":"Copyrights"},
  tc1_0:{"pt-PT":`Você não tem permissão para copiar ou modificar a plataforma, qualquer parte do aplicativo ou nossas marcas registradas de forma alguma.\n\n Você não tem permissão para tentar extrair o código-fonte do aplicativo e também não deve tentar traduzir a plataforma para outros idiomas ou criar versões derivadas. O aplicativo em si e todas as marcas registradas, direitos autorais, direitos de banco de dados e outros direitos de propriedade intelectual relacionados a ele ainda pertencem à ${document.location.hostname}.`,"en-US":`You are not permitted to copy or modify the Platform, any part of the App or our trademarks in any way.  You are not permitted to attempt to extract the application's source code, nor should you attempt to translate the platform into other languages or create derivative versions.  The application itself and all trademarks, copyrights, database rights and other intellectual property rights relating to it still belong to ${document.location.hostname}.`},
  
  tcTitle2:{"pt-PT":"Suas responsabilidades para segurança.", "en-US":"Your responsibilities for security."},
  tc2_0:{"pt-PT":`O aplicativo ${document.location.hostname} armazena e processa os dados pessoais que você nos forneceu para fornecer nosso Serviço. É sua responsabilidade manter seu dispositivo e acesso ao aplicativo seguros.`, "en-US":`The ${document.location.hostname} application stores and processes the personal data you provide to us to provide our Service.  It is your responsibility to keep your device and app access secure.`},
  tc2_1:{"pt-PT":`Na mesma linha, a ${document.location.hostname} nem sempre pode assumir a responsabilidade pela maneira como você usa a plataforma.`, "en-US":`In the same vein, ${document.location.hostname} cannot always take responsibility for the way you use the Platform.`},
  tc2_2:{"pt-PT":`Com relação à responsabilidade da ${document.location.hostname} pelo uso , quando você estiver usando a plataforma, é importante ter em mente que, embora nos esforcemos para garantir que ele esteja atualizado e correto o tempo todo, dependemos de terceiros para nos fornecer informações para que possamos disponibilizá-las para você. A ${document.location.hostname} não se responsabiliza por qualquer perda, direta ou indireta, que você sofra como resultado de confiar totalmente nesta funcionalidade do aplicativo.`,"en-US":`With respect to ${document.location.hostname}'s responsibility for use, when you are using the Platform it is important to keep in mind that whilst we strive to ensure that it is up to date and correct at all times, we rely on third parties to provide us with information so that we can make it available to you.  ${document.location.hostname} is not responsible for any loss, direct or indirect, that you suffer as a result of relying entirely on this functionality of the application.`},
  tcTitle3:{"pt-PT":"Contas múltiplas","en-US":"Multiple accounts"},
  tc3_0:{"pt-PT":`A ${document.location.hostname} está empenhada em garantir a melhor segurança no mercado tanto quanto na segurança dos dados. Por esse motivo, nos reservamos o direito de não aceitar o registro de duas contas ou mais com o mesmo e-mail ou número de telefone, qualquer suspeita de violação das regras a conta será banido.`,"en-US":`${document.location.hostname} is committed to ensuring the best security on the market as well as data security. For this reason, we reserve the right not to accept the registration of two or more accounts with the same email or telephone number, any suspected violation of the rules will result in the account being banned.`},
  tcTitle4:{"pt-PT":"Programa de parceiros","en-US":"Partner Program"},
  tc4_0:{"pt-PT":"Para entrar neste programa você tem que ter no mínimo 18 anos de idade." ,"en-US":"To enter this program you must be at least 18 years of age" },
  tc4_1:{"pt-PT":"Ao investir em frotras tenha em mente que né todos os investimentos sai como planejamos, portanto em caso de falha ou má gestão de estoques de produtos, reservamos o direito de remover a percentagem de lucro e reembolsar 70% do seu valor investido em três prestações no período de 3 meses." ,"en-US":"When investing in fleets, keep in mind that not all investments come out as planned, therefore in the event of failure or poor management of product stocks, we reserve the right to remove the profit percentage and refund 70% of the amount invested in three installments in period of 3 months." },
  tcTitle5:{"pt-PT":"Alterações nestes Termos e Condições", "en-US":"Changes to these Terms and Conditions"},
  tc5_0:{"pt-PT": "Podemos atualizar nossos Termos e Condições de tempos em tempos. Assim, você é aconselhado a revisar esta página periodicamente para quaisquer alterações. Iremos notificá-lo sobre quaisquer alterações publicando os novos Termos e Condições nesta página. Essas alterações entram em vigor imediatamente após serem publicadas nesta página.","en-US":"We may update our Terms and Conditions from time to time.  Accordingly, you are advised to review this page periodically for any changes.  We will notify you of any changes by posting the new Terms and Conditions on this page.  These changes are effective immediately upon being posted on this page." },
  
  howItWorks:{"pt-PT":"Como funciona","en-US":"How it works"},
  hiwTitle1:{"pt-PT":"Entenda como funciona","en-US":"Understand how it works"},
  hiw_1:{"pt-PT":"O primeiro passo é selecionar uma frota que melhor se adequa às suas necessidades e objetivos financeiros. Normalmente, este programa oferece uma variedade de opções.", "en-US": "The first step is to select a fleet that best suits your needs and financial goals. Typically, this program offers a variety of options."},
  hiw_2:{"pt-PT":"Após escolher a frota desejado, você deve adicionar o valor que pretende investir. A quantia mínima ou máxima necessário pode variar de acordo com a frota selecionada e com o montante disponível para investimento.", "en-US": "After choosing the desired fleet, you must add the amount you intend to invest.  The minimum or maximum amount required may vary according to the fleet selected and the amount available for investment."},
  hiw_3:{"pt-PT":"Ao adicionar o valor, o programa geralmente oferece diferentes métodos de pagamento. Você deve escolher a opção mais conveniente e seguir as instruções fornecidas pelo programa para efetuar o pagamento.", "en-US": "When adding the amount, the program usually offers different payment methods. You must choose the most convenient option and follow the instructions provided by the program to make the payment."},
  hiw_4:{"pt-PT":"Após o pagamento, é necessário aguardar até a data de retorno. Essa data é estabelecida previamente pelo programa, você será informado sobre ela durante o processo de investimento. Durante esse período, os especialistas em investimentos cuidarão do montante investido, visando obter os melhores resultados.", "en-US": "After payment, you must wait until the return date.  This date is established in advance by the program and you will be informed about it during the investment process.  During this period, investment specialists will take care of the amount invested, aiming to obtain the best results."},
  hiw_5:{"pt-PT":"Na data estipulada, o valor investido, juntamente com os lucros obtidos, estará disponível para resgate. Você poderá ter acesso a esse montante por meio do da sua pagina de perfil, que possibilita o levantamento dos fundos conforme as opções disponíveis, como transferência bancária ou transferência para uma conta específica.", "en-US": "On the stipulated date, the amount invested, together with the profits obtained, will be available for redemption.  You can access this amount through your profile page, which allows you to withdraw funds according to the available options, such as bank transfer or transfer to a specific account."},

}



export const quotes =[{
  quote:{"pt-PT":"A qualidade mais importante para um investidor é o temperamento, e não o intelecto.", "en-US":"The most important quality for an investor is temperament, and not intellect."},
  owner:"Warren Buffet,"
},{
  quote:{"pt-PT":"Em muitos aspectos, o mercado de ações é como o clima: se você não gosta das condições atuais, tudo o que precisa fazer é esperar.", "en-US":"In many ways, the stock market is like the weather, in that if you do not like the current conditions, all you have to do is wait."},
 owner:"Low Simpson"
},{
  quote:{"pt-PT":"Para ser um empresário e investidor de sucesso, você precisa ser emocionalmente neutro em relação a ganhar e perder.  Tudo faz parte do jogo.","en-US":"To be a successful business owner and investor, you have to be emotionally neutral to winning and losing. It is all part of the game."},
  owner:"Robert Kiyosaki"
},{
  quote:{"pt-PT":"Se você não encontrar uma maneira de ganhar dinheiro enquanto dorme, você trabalhará até morrer.","en-US":"If you don't find a way to make money while you sleep, you will work until you die"},
  owner:"Warren Buffet"
},
{
  quote:{"pt-PT":"Quantos milionários você conhece que ficaram ricos investindo em contas poupança?  Eu encerro meu caso.","en-US":"How many millionaires do you know have become wealthy by investing in a savings accounts? I rest my case."},
  owner:"Robert G. Allen"
},{
  quote:{"pt-PT":"A maneira mais fácil de administrar seu dinheiro é dar um passo de cada vez e não se preocupar em ser perfeito.", "en-US":"The easiest way to manage your money is to take it one step at a time and not worry about being perfect."},
  owner:"Ramit Sethi"
},{
  quote:{"pt-PT":"Risco vem de você não saber o que está fazendo.","en-US":"Risk comes from not knowing what you are doing."},
  owner:"Warren Buffet"
},{
  quote:{"pt-PT":"Uma jornada de mil quilômetros precisa começar com um simples passo.", "en-US":"A journey of a thousand kilometers must begin with a single step."},
  owner:"Lao Tzu"}
];
